pull_request_rules:
    - name: merge pull requests from dependabot if CI passes
      conditions:
      - author='dependabot <noreply@github.com>'
      - status-success=continuous-integration/travis/pr
      actions:
        merge:
          method: merge
