name: .NET Nanoframework

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  Build:
    strategy:
      matrix:
        configuration: [Debug, Release]
        
    runs-on: windows-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    steps:
    - name: Checkout Meteostanice
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Checkout NanoFramework Build Tools
      uses: actions/checkout@v2
      with:
       repository: nanoframework/nf-tools
       fetch-depth: 0
       path: ./nanoframework/
    
    - name: Setup NanoFramework Build Tools
      run: ./nanoframework/github-actions/install-nf-build-components.ps1
    
    - name: Build the NanoFramework
      run: ./build.ps1
      working-directory: "."
      env:
        Configuration: ${{ matrix.configuration }}
        Solution_Name: "Meteostanice.sln"
