name: .NET Nanoframework

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  Build:
    strategy:
      matrix:
        configuration: [Debug, Release]
        
    runs-on: windows-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      Solution_Name: Meteostanice.sln
    steps:
    - name: Checkout Meteostanice
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Checkout NanoFramework Build Tools
      uses: actions/checkout@v2
      with:
       repository: nanoframework/nf-tools
       fetch-depth: 0
       path: ./nanoframework/

    # Install the .NET Core workload
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    
    - name: Setup NanoFramework Build Tools
      run: ./nanoframework/github-actions/install-nf-build-components.ps1
    
    # Restore the application to populate the obj folder with RuntimeIdentifiers
    - name: Restore the application
      run: msbuild $env:Solution_Name /t:Restore /p:Configuration=$env:Configuration -m
      env:
        Configuration: ${{ matrix.configuration }}

    # Build the application
    - name: Build the nanoframework application
      run: msbuild $env:Solution_Name /t:Build /p:Configuration=$env:Configuration -m
      env:
        Configuration: ${{ matrix.configuration }}    
