# Copyright (c) .NET Foundation and Contributors
# https://github.com/networkfusion/MBN-TinyCLR/ original build, merged with https://github.com/TekuSP/Meteostanice-CSharp/

name: Build Nanoframework

on: [push, pull_request]

defaults:
  run:
    shell: pwsh



jobs:
  Build:
    strategy:
      matrix:
        configuration: [Debug, Release]
    name: Build NanoFramework SLN
    timeout-minutes: 15
    runs-on: windows-latest
    env:
      solution: 'Meteostanice.sln'
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: main
      - name: Checkout tools repo
        uses: actions/checkout@v2
        with:
          repository: nanoframework/nf-tools
          path: tools
      - name: Install build components for nanoFramework
        run: ./github-actions/install-nf-build-components.ps1
        working-directory: tools

      - name: Setup MSBuild Path
        uses: microsoft/setup-msbuild@v1.0.2

      # https://github.com/NuGet/setup-nuget
      - name: Install NuGet client
        uses: nuget/setup-nuget@v1
        with:
          nuget-version: '5.8.0'

      - name: Restore nugets
        run: nuget restore ${{ env.solution }} -ConfigFile NuGet.Config
        working-directory: main
        

      - name: Build NanoFramework Application
        run: msbuild ${{ env.solution }} /p:Configuration=$env:Configuration
        working-directory: main
        env:
          Configuration: ${{ matrix.configuration }}
