name: .NET Nanoframework

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: windows-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on
    steps:
    - name: Checkout Meteostanice
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    
    - name: Checkout NanoFramework Build Tools
      uses: actions/checkout@v2
      with:
       repository: nanoframework/nf-interpreter
       fetch-depth: 0
       path: ./nanoframework/

    # Install the .NET Core workload
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@2008f912f56e61277eefaac6d1888b750582aa16
      
    - name: Setup CMake.exe
      uses: lukka/get-cmake@v3.19.2
      
    - name: Setup NanoFramework Build Tools
      run: ./nanoframework/install-scripts/install-nf-tools.ps1 -TargetSeries ESP32
      
    - name: Build NanoFramework for ESP-32
      run: ./nanoframework/build.ps1 -Target ESP32_WROOM_32


    # Remove the pfx
    - name: Remove the pfx
      run: Remove-Item -path $env:Wap_Project_Directory\$env:Signing_Certificate

    # Upload the MSIX package: https://github.com/marketplace/actions/upload-artifact
    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: MSIX Package
        path: ${{ env.Wap_Project_Directory }}\AppPackages
